[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
num-bigint = "0.4.6"
serde = { version = "*", features = ["derive"] }
utils = { path = "../utils" }
#  持久化方案
rocksdb = "0.23.0"
